name: standalone_pub_server
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
 path: ^1.7.0
 shelf_router: ^0.7.4
 shelf_static: ^0.2.9+1
 crypto: ^2.1.3
 mongo_dart: ^0.4.4
 dart_jsonwebtoken: ^1.5.1
 envify: ^2.0.0

dev_dependencies:
  http: ^0.12.2
  pedantic: ^1.9.0
  test: ^1.14.4
  envify_generator: ^1.1.0
  build_runner: ^1.11.1
